services:
  frontend:
    build:
      context: ./services/frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend
    networks:
      - my-network

  backend:
    build:
      context: ./services/backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - my-network
    environment:
      - jwt_secret=${jwt_secret}

  db:
    build:
      context: ./services/db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - my-network

volumes:
  db-data:

networks:
  my-network:
