# OpenJDK (ARMv7) für Raspberry Pi als Basis
FROM openjdk:20

# Erstelle Arbeitsverzeichnis
WORKDIR /app

# Kopiere den Code
COPY . /app

# Baue die Anwendung
# RUN ./gradlew build

# Starte die Anwendung
# CMD ["./gradlew", "bootRun"]
